### ISSUE TITLE
Reason being

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/react-components-events-actions-and-stores#10]
Change "Reason being" to "The reason is" in the sentence below. Or, better yet, axe this sentence, because we don't know what imperative APIs are and we are not learning Angular:

"Reason being that React components are by definition declarative, while Angular heavily relies on imperative APIs."

Thank you.

**Comment by maxwellbenton** [comment]
Agreed. I've gone ahead and removed the whole sentence.

Thank you @ValerieHMoore!
