### ISSUE TITLE
What does "mock it out" mean?

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/react-components-events-actions-and-stores#11]
"Instead of restoring the store's state, we can also mock it out." What does mock it out mean -- comment it out, do a mockup, ???

Thank you.

**Comment by arye-eidelman** [comment]
[Mock](https://www.vocabulary.com/dictionary/mock) means to imitate or to fake it
In software, it usually means to give it fake data.
This is just like the mocked fetch responses that were used in many tests in the js section.
A mockup is an imitation of the final product with fake data, so it comes from the same word.

**Comment by maxwellbenton** [comment]
Hi @ValerieHMoore,

We've updated this section of the lesson's Readme to explain the testing issue more clearly and to explain what mocking out a store means in this case (using a provided package to create a fake store for testing), which should resolve this issue.

Thank you for contributing!
