### ISSUE TITLE
errors when running `npm run start`

### ISSUE THREAD

**Issue by Enoch2k2** [learn-co-curriculum/react-components-events-actions-and-stores#3]
@aturkewi @Lukeghenco 
So the issues are - 

![screen shot 2016-12-19 at 1 44 06 pm](https://cloud.githubusercontent.com/assets/16408135/21326998/a95ab262-c5f2-11e6-8272-bb9d53632c7a.png)

It for some reason doesn't like `import`.
The error goes away when you do `const React = require('react');` But then goes to the next import with the same error. They all go away when i require them instead of import.

Then it goes down to the `<` in the wrapper. Which errors out. Due to these errors when you navigate to `8080` in the lesson. Nothing gets displayed.

**Comment by Enoch2k2** [comment]
ha - so after going over what the issue might be i had a typo.... so ignore this please :) @aturkewi @Lukeghenco . Thanks!

**Comment by Enoch2k2** [comment]
The test issues are still there but we can see what's on the screen.

**Comment by aturkewi** [comment]
@Enoch2k2 if this is no longer an issue, I'm going to close it. I'm not sure what you mean by "The test issues are still there". If there is a problem with this lab regarding test issues, can you open a new issue on it?
Thanks!
