### ISSUE TITLE
What is a Flux store?

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/react-components-events-actions-and-stores#9]
We have not encountered the word "Flux" before, please define:
"If we end up constantly passing down tons of props, we should consider connecting the component in question with the respective Flux store."

Thank you.

**Comment by arye-eidelman** [comment]
Is flux here the [flux library](https://www.npmjs.com/package/flux) or the design pattern implemented by redux?

**Comment by maxwellbenton** [comment]
Hi @ValerieHMoore,

Thanks for pointing this out. We'v updated this lesson's Readme adding a brief bit of info on Flux (as a data pattern that Redux is based on) as well as a link to Flux's main site, which should help clarify this. 

Thank you for contributing!
